# Generated by Django 5.0.1 on 2024-07-02 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('idAtividade', models.IntegerField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=50)),
                ('data', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Competencias',
            fields=[
                ('idCompetencias', models.IntegerField(primary_key=True, serialize=False)),
                ('descricao', models.TextField()),
                ('op1', models.CharField(max_length=2000)),
                ('op2', models.CharField(max_length=2000)),
                ('op3', models.CharField(max_length=2000)),
                ('op4', models.CharField(max_length=2000)),
                ('op5', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Coordenadores',
            fields=[
                ('idCoordenadores', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('idDisciplina', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Professores',
            fields=[
                ('idProfessores', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('idCursos', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=50)),
                ('Coordenadores_idCoordenadores', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.coordenadores')),
            ],
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('nome', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('matricula', models.IntegerField(primary_key=True, serialize=False)),
                ('Cursos_idCursos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cursos')),
            ],
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('idNota', models.IntegerField(primary_key=True, serialize=False)),
                ('nota', models.CharField(max_length=50)),
                ('data', models.DateField()),
                ('Aluno_matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.aluno')),
                ('Atividade_idAtividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.atividade')),
                ('Competencias_idCompetencias', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.competencias')),
                ('Professores_idProfessores', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.professores')),
            ],
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('idTurma', models.IntegerField(primary_key=True, serialize=False)),
                ('semestre', models.CharField(max_length=100)),
                ('Disciplina_idDisciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.disciplina')),
                ('Professores_idProfessores', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.professores')),
            ],
        ),
        migrations.CreateModel(
            name='Turma_Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semestre', models.CharField(max_length=45)),
                ('Aluno_matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.aluno')),
                ('Disciplina_idDisciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.disciplina')),
                ('Turma_idTurma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.turma')),
            ],
            options={
                'unique_together': {('Turma_idTurma', 'Disciplina_idDisciplina')},
            },
        ),
    ]
