# Generated by Django 5.0 on 2024-08-21 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Coordenador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('codigo', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='nota',
            name='Competencias_idCompetencias',
        ),
        migrations.RemoveField(
            model_name='cursos',
            name='Coordenadores_idCoordenadores',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='Cursos_idCursos',
        ),
        migrations.RemoveField(
            model_name='nota',
            name='Professores_idProfessores',
        ),
        migrations.RemoveField(
            model_name='turma',
            name='Professores_idProfessores',
        ),
        migrations.AlterUniqueTogether(
            name='turma_aluno',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='turma_aluno',
            name='Aluno_matricula',
        ),
        migrations.RemoveField(
            model_name='turma_aluno',
            name='Disciplina_idDisciplina',
        ),
        migrations.RemoveField(
            model_name='turma_aluno',
            name='Turma_idTurma',
        ),
        migrations.RenameField(
            model_name='nota',
            old_name='Atividade_idAtividade',
            new_name='atividade',
        ),
        migrations.RenameField(
            model_name='turma',
            old_name='Disciplina_idDisciplina',
            new_name='disciplina',
        ),
        migrations.RemoveField(
            model_name='atividade',
            name='idAtividade',
        ),
        migrations.RemoveField(
            model_name='disciplina',
            name='idDisciplina',
        ),
        migrations.RemoveField(
            model_name='nota',
            name='Aluno_matricula',
        ),
        migrations.RemoveField(
            model_name='nota',
            name='idNota',
        ),
        migrations.RemoveField(
            model_name='turma',
            name='idTurma',
        ),
        migrations.AddField(
            model_name='atividade',
            name='disciplina',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.disciplina'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='atividade',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='disciplina',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nota',
            name='aluno',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='notas_recebidas', to='api.aluno'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nota',
            name='avaliador',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='notas_avaliadas', to='api.aluno'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nota',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='turma',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aluno',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='nome',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='titulo',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='codigo',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='nome',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='nota',
            name='nota',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]),
        ),
        migrations.AlterField(
            model_name='turma',
            name='semestre',
            field=models.CharField(max_length=20),
        ),
        migrations.AddField(
            model_name='nota',
            name='competencia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.competencia'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='disciplina',
            name='coordenador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.coordenador'),
        ),
        migrations.AddField(
            model_name='coordenador',
            name='cursos',
            field=models.ManyToManyField(related_name='coordenadores', to='api.curso'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='curso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.curso'),
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('disciplina', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.disciplina')),
            ],
        ),
        migrations.AddField(
            model_name='atividade',
            name='professor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.professor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='turma',
            name='professor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.professor'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='TurmaAluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semestre', models.CharField(max_length=20)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.aluno')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.disciplina')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.turma')),
            ],
        ),
        migrations.DeleteModel(
            name='Competencias',
        ),
        migrations.DeleteModel(
            name='Coordenadores',
        ),
        migrations.DeleteModel(
            name='Cursos',
        ),
        migrations.DeleteModel(
            name='Professores',
        ),
        migrations.DeleteModel(
            name='Turma_Aluno',
        ),
    ]
