# Generated by Django 5.0 on 2024-08-21 00:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_competencia_coordenador_curso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='disciplina',
            field=models.ForeignKey(default=201, on_delete=django.db.models.deletion.CASCADE, to='api.disciplina'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='disciplina',
            field=models.ForeignKey(default=201, on_delete=django.db.models.deletion.CASCADE, to='api.disciplina'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='disciplina',
            field=models.ForeignKey(default=201, on_delete=django.db.models.deletion.CASCADE, to='api.disciplina'),
        ),
        migrations.AlterField(
            model_name='turmaaluno',
            name='disciplina',
            field=models.ForeignKey(default=201, on_delete=django.db.models.deletion.CASCADE, to='api.disciplina'),
        ),
    ]
