# Generated by Django 5.0 on 2024-08-21 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_atividade_disciplina_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nota',
            name='avaliador',
        ),
        migrations.RemoveField(
            model_name='turmaaluno',
            name='aluno',
        ),
        migrations.RemoveField(
            model_name='nota',
            name='aluno',
        ),
        migrations.RemoveField(
            model_name='atividade',
            name='disciplina',
        ),
        migrations.RemoveField(
            model_name='atividade',
            name='professor',
        ),
        migrations.RemoveField(
            model_name='nota',
            name='atividade',
        ),
        migrations.RemoveField(
            model_name='nota',
            name='competencia',
        ),
        migrations.RemoveField(
            model_name='coordenador',
            name='cursos',
        ),
        migrations.RemoveField(
            model_name='disciplina',
            name='coordenador',
        ),
        migrations.RemoveField(
            model_name='turmaaluno',
            name='disciplina',
        ),
        migrations.RemoveField(
            model_name='turma',
            name='disciplina',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='disciplina',
        ),
        migrations.RemoveField(
            model_name='turma',
            name='professor',
        ),
        migrations.RemoveField(
            model_name='turmaaluno',
            name='turma',
        ),
        migrations.DeleteModel(
            name='Aluno',
        ),
        migrations.DeleteModel(
            name='Atividade',
        ),
        migrations.DeleteModel(
            name='Competencia',
        ),
        migrations.DeleteModel(
            name='Nota',
        ),
        migrations.DeleteModel(
            name='Curso',
        ),
        migrations.DeleteModel(
            name='Coordenador',
        ),
        migrations.DeleteModel(
            name='Disciplina',
        ),
        migrations.DeleteModel(
            name='Professor',
        ),
        migrations.DeleteModel(
            name='Turma',
        ),
        migrations.DeleteModel(
            name='TurmaAluno',
        ),
    ]
