# Generated by Django 4.2.16 on 2025-03-13 18:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('idAluno', models.AutoField(primary_key=True, serialize=False)),
                ('nomeAluno', models.CharField(max_length=255)),
                ('emailAluno', models.EmailField(max_length=254, unique=True)),
                ('senhaAluno', models.CharField(max_length=128)),
                ('matriculaAluno', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('idAtividade', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('data', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Competencia',
            fields=[
                ('idCompetencia', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('idCurso', models.AutoField(primary_key=True, serialize=False)),
                ('nomeCurso', models.CharField(max_length=30)),
                ('codigoCurso', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('idDisciplina', models.AutoField(primary_key=True, serialize=False)),
                ('nomeDisciplina', models.CharField(max_length=60)),
                ('codigoDisciplina', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('idTurma', models.AutoField(primary_key=True, serialize=False)),
                ('sigla', models.CharField(blank=True, max_length=20, null=True)),
                ('semestre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TurmaAluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semestre', models.CharField(max_length=30)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.aluno')),
                ('disciplina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.disciplina')),
                ('turma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.turma')),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('idProfessor', models.AutoField(primary_key=True, serialize=False)),
                ('nomeProf', models.CharField(max_length=255)),
                ('emailProf', models.EmailField(max_length=254, unique=True)),
                ('senhaProf', models.CharField(max_length=128)),
                ('disciplinaProf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.disciplina')),
            ],
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('data', models.DateField()),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_recebidas', to='project.aluno')),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.atividade')),
                ('avaliador_aluno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notas_dadas_aluno', to='project.aluno')),
                ('avaliador_professor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notas_dadas_professor', to='project.professor')),
                ('competencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.competencia')),
            ],
        ),
        migrations.CreateModel(
            name='Coordenador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeCoord', models.CharField(max_length=255)),
                ('emailCoord', models.EmailField(max_length=254, unique=True)),
                ('senhaCoord', models.CharField(max_length=128)),
                ('cursoCoord', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.curso')),
            ],
        ),
        migrations.AddField(
            model_name='atividade',
            name='atividadeDisc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.disciplina'),
        ),
        migrations.AddField(
            model_name='atividade',
            name='atividadeProf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.professor'),
        ),
        migrations.AddField(
            model_name='atividade',
            name='atividadeTurma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.turma'),
        ),
    ]
