# Generated by Django 5.1.7 on 2025-03-25 00:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semestre',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ano', models.IntegerField()),
                ('periodo', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='atividade',
            old_name='data',
            new_name='dataEntrega',
        ),
        migrations.RenameField(
            model_name='atividade',
            old_name='idAtividade',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='competencia',
            old_name='idCompetencia',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='curso',
            old_name='idCurso',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='disciplina',
            old_name='idDisciplina',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='turma',
            old_name='idTurma',
            new_name='id',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='matriculaAluno',
        ),
        migrations.RemoveField(
            model_name='atividade',
            name='atividadeDisc',
        ),
        migrations.RemoveField(
            model_name='atividade',
            name='atividadeProf',
        ),
        migrations.RemoveField(
            model_name='atividade',
            name='atividadeTurma',
        ),
        migrations.RemoveField(
            model_name='coordenador',
            name='cursoCoord',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='codigoCurso',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='nomeCurso',
        ),
        migrations.RemoveField(
            model_name='disciplina',
            name='codigoDisciplina',
        ),
        migrations.RemoveField(
            model_name='disciplina',
            name='nomeDisciplina',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='disciplinaProf',
        ),
        migrations.RemoveField(
            model_name='turma',
            name='sigla',
        ),
        migrations.AlterUniqueTogether(
            name='turmaaluno',
            unique_together={('turma', 'aluno')},
        ),
        migrations.AddField(
            model_name='aluno',
            name='curso',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='alunos', to='project.curso'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aluno',
            name='matricula',
            field=models.CharField(default=1, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='atividade',
            name='descricao',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='atividade',
            name='turma',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='atividades', to='project.turma'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='competencia',
            name='nome',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coordenador',
            name='curso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coordenadores', to='project.curso'),
        ),
        migrations.AddField(
            model_name='curso',
            name='nome',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='disciplina',
            name='codigo',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='disciplina',
            name='curso',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='disciplinas', to='project.curso'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='disciplina',
            name='nome',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nota',
            name='dataAvaliacao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='turma',
            name='codigo',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='turma',
            name='disciplina',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='turmas', to='project.disciplina'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='turma',
            name='professor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='turmas', to='project.professor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aluno',
            name='nomeAluno',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='senhaAluno',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='titulo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='coordenador',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='coordenador',
            name='nomeCoord',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='coordenador',
            name='senhaCoord',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='nota',
            name='competencia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='project.competencia'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='nota',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='nota',
            name='nota',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='professor',
            name='nomeProf',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='professor',
            name='senhaProf',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='turmaaluno',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turmas', to='project.aluno'),
        ),
        migrations.AlterField(
            model_name='turmaaluno',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='turmaaluno',
            name='turma',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to='project.turma'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('concluida', models.BooleanField(default=False)),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='project.atividade')),
                ('avaliado_aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_recebidas', to='project.aluno')),
                ('avaliador_aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_realizadas', to='project.aluno')),
            ],
            options={
                'unique_together': {('avaliador_aluno', 'avaliado_aluno', 'atividade')},
            },
        ),
        migrations.AddField(
            model_name='nota',
            name='avaliacao',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='project.avaliacao'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='nota',
            unique_together={('avaliacao', 'competencia')},
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('alunos', models.ManyToManyField(related_name='grupos', to='project.aluno')),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos', to='project.atividade')),
            ],
        ),
        migrations.AlterField(
            model_name='turma',
            name='semestre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turmas', to='project.semestre'),
        ),
        migrations.RemoveField(
            model_name='turmaaluno',
            name='disciplina',
        ),
        migrations.RemoveField(
            model_name='turmaaluno',
            name='semestre',
        ),
        migrations.RemoveField(
            model_name='nota',
            name='aluno',
        ),
        migrations.RemoveField(
            model_name='nota',
            name='atividade',
        ),
        migrations.RemoveField(
            model_name='nota',
            name='avaliador_aluno',
        ),
        migrations.RemoveField(
            model_name='nota',
            name='avaliador_professor',
        ),
        migrations.RemoveField(
            model_name='nota',
            name='data',
        ),
    ]
