# Generated by Django 5.1.7 on 2025-03-27 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_semestre_rename_data_atividade_dataentrega_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nomeAdmin', models.CharField(max_length=100)),
                ('emailAdmin', models.EmailField(max_length=254, unique=True)),
                ('senhaAdmin', models.CharField(max_length=100)),
            ],
        ),
    ]
