# Generated by Django 5.1.7 on 2025-04-02 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_notificacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividade',
            name='competencias',
            field=models.ManyToManyField(blank=True, related_name='atividades', to='project.competencia'),
        ),
    ]
