# Generated by Django 5.1.7 on 2025-09-14 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_atividade_competencias'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao',
            name='is_self_assessment',
            field=models.BooleanField(default=False, help_text='Indica se é uma auto-avaliação'),
        ),
    ]
