# Generated by Django 5.1.7

from django.db import migrations


def update_existing_evaluations(apps, schema_editor):
    """
    Update existing evaluations to set is_self_assessment appropriately
    """
    Avaliacao = apps.get_model('project', 'Avaliacao')
    
    # For now, just set all existing evaluations as peer evaluations (False)
    # Since we don't have self-evaluations in the existing data
    Avaliacao.objects.all().update(is_self_assessment=False)


def reverse_update_existing_evaluations(apps, schema_editor):
    """
    Reverse the update - set all is_self_assessment back to False
    """
    Avaliacao = apps.get_model('project', 'Avaliacao')
    Avaliacao.objects.all().update(is_self_assessment=False)


def reverse_update_existing_evaluations(apps, schema_editor):
    """
    Reverse the update - set all is_self_assessment back to False
    """
    Avaliacao = apps.get_model('project', 'Avaliacao')
    Avaliacao.objects.all().update(is_self_assessment=False)


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_add_self_assessment_field'),
    ]

    operations = [
        migrations.RunPython(
            update_existing_evaluations,
            reverse_update_existing_evaluations
        ),
    ]
