# Generated by Django 5.1.7

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_update_existing_evaluations'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='avaliacao',
            unique_together={('avaliador_aluno', 'avaliado_aluno', 'atividade', 'is_self_assessment')},
        ),
    ]
