# Generated by Django 5.0.3 on 2025-09-14 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_alter_avaliacao_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='avaliacao',
            unique_together={('avaliador_aluno', 'avaliado_aluno', 'atividade')},
        ),
    ]
