# Generated by Django 5.0.1 on 2024-01-28 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='q1',
            name='resposta',
        ),
        migrations.AddField(
            model_name='q1',
            name='opcao',
            field=models.CharField(choices=[('A', 'Opção A'), ('B', 'Opção B'), ('C', 'Opção C'), ('D', 'Opção D'), ('E', 'Opção E')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
